In [1]:
 %config Completer.use_jedi = False

In [4]:
import networkx as nx
import community as c
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
os.chdir('/Users/Natalia/Desktop/Master/Feb-2021/Modern Data Analytics/Project/All Fillings')

Files with all of the fillings from one period

In [ ]:
quarter=pd.read_csv('1Q_2021_All.csv')
investors=pd.read_csv('investors.csv')

Principal investors in farmaceutical companies in the first quarter of 2021

In [ ]:
inv=investors["investor"].tolist()
inv

['BERKSHIRE ASSET MANAGEMENT LLC/PA',
 'BlackRock Inc.',
 'CREDIT SUISSE AG/',
 'DRW Securities, LLC',
 'FMR LLC',
 'JANUS HENDERSON GROUP PLC',
 'Nuveen Asset Management, LLC',
 'Ally Financial Inc.',
 'KORNITZER CAPITAL MANAGEMENT INC /KS',
 'Kovitz Investment Group Partners, LLC',
 'McGinn Investment Management, Inc.',
 'PARAMETRIC PORTFOLIO ASSOCIATES LLC',
 'PNC FINANCIAL SERVICES GROUP, INC.',
 'Pacer Advisors, Inc.',
 'BAILLIE GIFFORD & CO',
 'BANK OF AMERICA CORP /DE/',
 'CALIFORNIA PUBLIC EMPLOYEES RETIREMENT SYSTEM',
 'GOLDMAN SACHS GROUP INC',
 'HAP Trading, LLC',
 'HILLHOUSE CAPITAL ADVISORS, LTD.',
 'Laurion Capital Management LP',
 'MILLENNIUM MANAGEMENT LLC',
 'MORGAN STANLEY',
 'PLATINUM INVESTMENT MANAGEMENT LTD',
 'PRICE T ROWE ASSOCIATES INC /MD/',
 'SG3 Management, LLC',
 'Capital World Investors',
 'DIAMOND HILL CAPITAL MANAGEMENT INC',
 'First American Bank',
 'LETKO, BROSSEAU & ASSOCIATES INC',
 'Neuberger Berman Group LLC',
 'RENAISSANCE TECHNOLOGIES LLC',
 'SUSQUEHANNA INTERNATIONAL GROUP, LLP',
 'Bank of New York Mellon Corp',
 'Calamos Advisors LLC',
 'Capital Research Global Investors',
 'LAZARD ASSET MANAGEMENT LLC',
 'WELLS FARGO & COMPANY/MN',
 'Allianz Asset Management GmbH',
 'CITADEL ADVISORS LLC',
 'DODGE & COX',
 'NORTHERN TRUST CORP',
 'PRIMECAP MANAGEMENT CO/CA/',
 'STATE STREET CORP',
 'DEUTSCHE BANK AG\\',
 'Fisher Asset Management, LLC',
 'REGENTS OF THE UNIVERSITY OF CALIFORNIA',
 'CANANDAIGUA NATIONAL CORP',
 'Cullen Capital Management, LLC',
 'LSV ASSET MANAGEMENT',
 'RENAISSANCE GROUP LLC',
 'RHUMBLINE ADVISERS',
 'RIVERBRIDGE PARTNERS LLC',
 'SCOUT INVESTMENTS, INC.',
 'THOMAS WHITE INTERNATIONAL LTD',
 'Clal Insurance Enterprises Holdings Ltd',
 'EATON VANCE MANAGEMENT',
 'FRANKLIN RESOURCES INC',
 'Invesco Ltd.',
 'LORD, ABBETT & CO. LLC',
 'Redmile Group, LLC',
 'Neumann Advisory Hong Kong Ltd',
 'ORBIMED ADVISORS LLC',
 'Spark Investment Management LLC',
 'Vivo Capital, LLC']

In [ ]:
quarter

,Unnamed: 0,name,cik,state,issuers,cussip,shares,shares_type
0,0,Pensionfund DSM Netherlands,1297731,P7,3M CO,88579Y101,21700,SH
1,1,Pensionfund DSM Netherlands,1297731,P7,ABBVIE INC,00287Y109,52100,SH
2,2,Pensionfund DSM Netherlands,1297731,P7,AFLAC INC,001055102,56900,SH
3,3,Pensionfund DSM Netherlands,1297731,P7,AGNC INVESTMENT CORP,00123Q104,127500,SH
4,4,Pensionfund DSM Netherlands,1297731,P7,ALEXANDRIA REAL ESTATE EQUIT,015271109,15700,SH
...,...,...,...,...,...,...,...,...
2198425,2198425,SWS Partners,1731731,OH,Wells Fargo &amp; Co,808524300,858,SH
2198426,2198426,SWS Partners,1731731,OH,Westrock Co,808524409,1261,SH
2198427,2198427,SWS Partners,1731731,OH,Workday Inc Class A,808524508,102375,SH
2198428,2198428,SWS Partners,1731731,OH,XTRCKR MSCI EAFE HG DV YLD Eq ETF,808524607,44203,SH
2198429,2198429,SWS Partners,1731731,OH,Zillow Group Inc,808524706,133398,SH

If there is shares bellow 10, we assume there is an error and those entries are removed

In [ ]:
quarter['shares']=[float(i) for i in quarter['shares']]
quarter = quarter[quarter.shares >= 10]
quarter

,Unnamed: 0,name,cik,state,issuers,cussip,shares,shares_type
0,0,Pensionfund DSM Netherlands,1297731,P7,3M CO,88579Y101,21700.0,SH
1,1,Pensionfund DSM Netherlands,1297731,P7,ABBVIE INC,00287Y109,52100.0,SH
2,2,Pensionfund DSM Netherlands,1297731,P7,AFLAC INC,001055102,56900.0,SH
3,3,Pensionfund DSM Netherlands,1297731,P7,AGNC INVESTMENT CORP,00123Q104,127500.0,SH
4,4,Pensionfund DSM Netherlands,1297731,P7,ALEXANDRIA REAL ESTATE EQUIT,015271109,15700.0,SH
...,...,...,...,...,...,...,...,...
2198425,2198425,SWS Partners,1731731,OH,Wells Fargo &amp; Co,808524300,858.0,SH
2198426,2198426,SWS Partners,1731731,OH,Westrock Co,808524409,1261.0,SH
2198427,2198427,SWS Partners,1731731,OH,Workday Inc Class A,808524508,102375.0,SH
2198428,2198428,SWS Partners,1731731,OH,XTRCKR MSCI EAFE HG DV YLD Eq ETF,808524607,44203.0,SH
2198429,2198429,SWS Partners,1731731,OH,Zillow Group Inc,808524706,133398.0,SH

We keep only the observations for the investors listes above

In [ ]:
quarter_filtered_investor=quarter[quarter['name'].isin(inv)]
quarter_filtered_investor

,Unnamed: 0,name,cik,state,issuers,cussip,shares,shares_type
3536,3536,Neumann Advisory Hong Kong Ltd,1727862,K3,FACEBOOK INC,30303M102,116572.0,SH
3537,3537,Neumann Advisory Hong Kong Ltd,1727862,K3,ALIBABA GROUP HOLDING LIMITED,01609W102,170000.0,SH
3538,3538,Neumann Advisory Hong Kong Ltd,1727862,K3,AGORA INC,00851L103,2192934.0,SH
3539,3539,Neumann Advisory Hong Kong Ltd,1727862,K3,TWILIO INC,90138F102,379574.0,SH
3540,3540,Neumann Advisory Hong Kong Ltd,1727862,K3,XPENG INC,98422D105,205000.0,SH
...,...,...,...,...,...,...,...,...
2018691,2018691,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,ISHARES TR,92939U106,2899.0,SH
2018692,2018692,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,ISHARES TR,92936u109,274288.0,SH
2018693,2018693,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,ISHARES TR,931427108,7556.0,SH
2018694,2018694,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,ISHARES TR,931142103,160779.0,SH
2018695,2018695,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,ISHARES TR,94106L109,228345.0,SH

And then, only their investments in pharmaceutical companies

In [ ]:
phar_2 = quarter_filtered_investor[quarter_filtered_investor['issuers'].str.contains('pfizer', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('astrazeneca', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('moderna', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('sinovac', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('curevac', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('merck', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('themis', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('glaxosmithkline', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('novartis', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('roche', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('sanofi', na = False, case=False) |
       quarter_filtered_investor['issuers'].str.contains('bayer', na = False, case=False)]

phar_2

,Unnamed: 0,name,cik,state,issuers,cussip,shares,shares_type
3543,3543,Neumann Advisory Hong Kong Ltd,1727862,K3,SINOVAC BIOTECH LTD,P8696W104,315586.0,SH
4319,4319,First American Bank,1291422,IL,GLAXOSMITHKLINE CAP INC,377372AL1,3600000.0,PRN
4387,4387,First American Bank,1291422,IL,MERCK &amp; CO INC NEW,58933Y105,117099.0,SH
4388,4388,First American Bank,1291422,IL,MERCK &amp; CO INC NEW,58933Y105,450.0,SH
4417,4417,First American Bank,1291422,IL,PFIZER INC COM,717081103,132182.0,SH
...,...,...,...,...,...,...,...,...
2014526,2014526,DEUTSCHE BANK AG\,948046,2M,SANOFI,80013R206,210367.0,SH
2014990,2014990,DEUTSCHE BANK AG\,948046,2M,SINOPEC SHANGHAI PETROCHEMIC,82900L102,19170.0,SH
2018493,2018493,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,ASTRAZENECA PLC,98986TAB4,8157000.0,PRN
2018585,2018585,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,MERCK &amp; CO. INC,494368103,112090.0,SH
2018609,2018609,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,PFIZER INC,65339f101,32117.0,SH

In [ ]:
phar_2.loc[phar_2['issuers'].str.contains('pfizer', case=False, na=False), 'issuers']= 'Pfizer'
phar_2.loc[phar_2['issuers'].str.contains('astrazeneca', case=False, na=False), 'issuers'] = 'Astrazeneca'
phar_2.loc[phar_2['issuers'].str.contains('moderna', case=False, na=False), 'issuers'] = 'Moderna'
phar_2.loc[phar_2['issuers'].str.contains('sinovac', case=False, na=False), 'issuers'] = 'Sinovac'
phar_2.loc[phar_2['issuers'].str.contains('curevac', case=False, na=False), 'issuers'] = 'Curevac'
phar_2.loc[phar_2['issuers'].str.contains('merck', case=False, na=False), 'issuers'] = 'Merck'
phar_2.loc[phar_2['issuers'].str.contains('themis', case=False, na=False), 'issuers'] = 'Themis'
phar_2.loc[phar_2['issuers'].str.contains('glaxosmithkline', case=False, na=False), 'issuers'] = 'Glaxosmithkline'
phar_2.loc[phar_2['issuers'].str.contains('novartis', case=False, na=False), 'issuers'] = 'Novartis'
phar_2.loc[phar_2['issuers'].str.contains('roche', case=False, na=False), 'issuers'] = 'Roche'
phar_2.loc[phar_2['issuers'].str.contains('sanofi', case=False, na=False), 'issuers'] = 'Sanofi'
phar_2.loc[phar_2['issuers'].str.contains('bayer', case=False, na=False), 'issuers'] = 'Bayer'
phar_2

C:\Users\Natalia\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Unnamed: 0,name,cik,state,issuers,cussip,shares,shares_type
3543,3543,Neumann Advisory Hong Kong Ltd,1727862,K3,Sinovac,P8696W104,315586.0,SH
4319,4319,First American Bank,1291422,IL,Glaxosmithkline,377372AL1,3600000.0,PRN
4387,4387,First American Bank,1291422,IL,Merck,58933Y105,117099.0,SH
4388,4388,First American Bank,1291422,IL,Merck,58933Y105,450.0,SH
4417,4417,First American Bank,1291422,IL,Pfizer,717081103,132182.0,SH
...,...,...,...,...,...,...,...,...
2014526,2014526,DEUTSCHE BANK AG\,948046,2M,Sanofi,80013R206,210367.0,SH
2014990,2014990,DEUTSCHE BANK AG\,948046,2M,Roche,82900L102,19170.0,SH
2018493,2018493,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,Astrazeneca,98986TAB4,8157000.0,PRN
2018585,2018585,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,Merck,494368103,112090.0,SH
2018609,2018609,BERKSHIRE ASSET MANAGEMENT LLC/PA,949012,PA,Pfizer,65339f101,32117.0,SH

In [ ]:
os.chdir('/Users/Natalia/Desktop/Master/Feb-2021/Modern Data Analytics/Project/Filtered Fillings')

In [ ]:
phar_2.to_csv('2021Q1_Filtered.csv',index=False)

In [ ]:
phar_2 = pd.